import { useState, useEffect } from 'react';
import type { FC } from 'react';
import ContextHeader from '../components/layout/ContextHeader';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import { jobs } from '../data/jobs';
import { generateDailyDigest, getDigestKey } from '../utils/digestEngine';
import { calculateMatchScore, getScoreBadgeVariant } from '../utils/matchEngine';
import { getStatusBadgeVariant } from '../utils/statusTracker';
import type { Preferences } from '../types/preferences';
import type { Job } from '../types/job';
import type { StatusUpdate } from '../types/status';

const DigestPage: FC = () => {
    const [preferences, setPreferences] = useState<Preferences | null>(null);
    const [digestJobs, setDigestJobs] = useState<Job[]>([]);
    const [statusHistory, setStatusHistory] = useState<StatusUpdate[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);

    useEffect(() => {
        const savedPrefs = localStorage.getItem('jobTrackerPreferences');
        if (savedPrefs) {
            setPreferences(JSON.parse(savedPrefs));
        }

        const todayKey = getDigestKey();
        const existingDigest = localStorage.getItem(todayKey);
        if (existingDigest) {
            setDigestJobs(JSON.parse(existingDigest));
        }

        const history = JSON.parse(localStorage.getItem('jobTrackerStatusHistory') || '[]');
        setStatusHistory(history);
    }, []);

    const handleGenerate = () => {
        if (!preferences) return;

        setIsGenerating(true);
        setTimeout(() => {
            const digest = generateDailyDigest(jobs, preferences);
            setDigestJobs(digest);
            localStorage.setItem(getDigestKey(), JSON.stringify(digest));
            setIsGenerating(false);
        }, 1200);
    };

    const copyToClipboard = () => {
        const dateStr = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' });
        let text = `My 9AM Job Digest - ${dateStr}\n\n`;

        digestJobs.forEach((job, i) => {
            const score = calculateMatchScore(job, preferences!);
            text += `${i + 1}. ${job.title} at ${job.company}\n`;
            text += `   Match Score: ${score}%\n`;
            text += `   Location: ${job.location} | Exp: ${job.experience}\n`;
            text += `   Apply: ${job.applyUrl}\n\n`;
        });

        text += "Generated by Job Notification Tracker.";
        navigator.clipboard.writeText(text);
        alert('Digest copied to clipboard!');
    };

    const createEmailDraft = () => {
        const dateStr = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' });
        const subject = encodeURIComponent(`My 9AM Job Digest - ${dateStr}`);

        let body = `Top 10 jobs matched for you today:\n\n`;
        digestJobs.forEach((job, i) => {
            const score = calculateMatchScore(job, preferences!);
            body += `${i + 1}. ${job.title} (${job.company}) - ${score}% Match\n`;
            body += `Link: ${job.applyUrl}\n\n`;
        });

        window.location.href = `mailto:?subject=${subject}&body=${encodeURIComponent(body)}`;
    };

    return (
        <div>
            <ContextHeader title="Daily Digest" subtitle="Your personalized morning briefing." />

            <div className="container" style={{ padding: 'var(--space-4) var(--space-3)' }}>

                {/* Status Updates Section */}
                {statusHistory.length > 0 && (
                    <Card style={{ marginBottom: 'var(--space-6)', padding: 'var(--space-4)' }}>
                        <h3 style={{ fontSize: '18px', marginBottom: 'var(--space-3)' }}>Recent Status Updates</h3>
                        <div style={{ display: 'grid', gap: '12px' }}>
                            {statusHistory.map((update, idx) => (
                                <div key={idx} style={{
                                    display: 'flex',
                                    justifyContent: 'space-between',
                                    alignItems: 'center',
                                    paddingBottom: '8px',
                                    borderBottom: idx === statusHistory.length - 1 ? 'none' : '1px solid rgba(17,17,17,0.05)'
                                }}>
                                    <div>
                                        <div style={{ fontSize: '14px', fontWeight: 600 }}>{update.jobTitle}</div>
                                        <div style={{ fontSize: '12px', color: 'rgba(17,17,17,0.5)' }}>
                                            {update.company} • {new Date(update.timestamp).toLocaleDateString()}
                                        </div>
                                    </div>
                                    <Badge variant={getStatusBadgeVariant(update.status)}>{update.status}</Badge>
                                </div>
                            ))}
                        </div>
                    </Card>
                )}

                {!preferences ? (
                    <Card style={{ textAlign: 'center', padding: 'var(--space-6)' }}>
                        <div style={{ fontSize: '18px', fontWeight: 600, color: 'var(--accent-color)', marginBottom: '12px' }}>
                            Precision parameters not found.
                        </div>
                        <p style={{ color: 'rgba(17, 17, 17, 0.6)', marginBottom: 'var(--space-4)' }}>
                            Set preferences to generate a personalized daily digest.
                        </p>
                        <Button onClick={() => window.location.href = '/settings'}>Go to Settings</Button>
                    </Card>
                ) : digestJobs.length === 0 ? (
                    <Card style={{ textAlign: 'center', padding: 'var(--space-6)' }}>
                        <h2 style={{ marginBottom: '12px' }}>Ready for your daily briefing?</h2>
                        <p style={{ color: 'rgba(17, 17, 17, 0.6)', marginBottom: 'var(--space-4)' }}>
                            We'll curate the top 10 positions matching your precision profile.
                        </p>
                        <Button onClick={handleGenerate} disabled={isGenerating}>
                            {isGenerating ? 'Curating Results...' : "Generate Today's 9AM Digest (Simulated)"}
                        </Button>
                        <div style={{ marginTop: '24px', fontSize: '11px', color: 'rgba(17, 17, 17, 0.4)', fontStyle: 'italic' }}>
                            Demo Mode: Daily 9AM trigger simulated manually.
                        </div>
                    </Card>
                ) : (
                    <div style={{ maxWidth: '700px', margin: '0 auto' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 'var(--space-4)' }}>
                            <Button variant="secondary" onClick={() => setDigestJobs([])}>Reset View</Button>
                            <div style={{ display: 'flex', gap: '8px' }}>
                                <Button variant="secondary" onClick={copyToClipboard}>Copy Digest</Button>
                                <Button onClick={createEmailDraft}>Create Email Draft</Button>
                            </div>
                        </div>

                        <Card style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--border-color)', boxShadow: '0 4px 20px rgba(0,0,0,0.05)' }}>
                            <div style={{ backgroundColor: 'var(--accent-color)', color: 'white', padding: '32px 24px', textAlign: 'center' }}>
                                <div style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '8px', opacity: 0.8 }}>KodNest Premium</div>
                                <h2 style={{ fontSize: '24px', marginBottom: '4px' }}>Top 10 Jobs For You</h2>
                                <div style={{ fontSize: '14px', opacity: 0.9 }}>9AM Digest — {new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</div>
                            </div>

                            <div style={{ padding: '24px', backgroundColor: '#FFFFFF' }}>
                                {digestJobs.map((job, idx) => {
                                    const score = calculateMatchScore(job, preferences);
                                    return (
                                        <div key={job.id} style={{
                                            padding: '20px 0',
                                            borderBottom: idx === digestJobs.length - 1 ? 'none' : '1px solid rgba(17,17,17,0.05)',
                                            display: 'flex',
                                            justifyContent: 'space-between',
                                            alignItems: 'center'
                                        }}>
                                            <div>
                                                <div style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color: 'rgba(17,17,17,0.4)', marginBottom: '4px' }}>
                                                    {job.company}
                                                </div>
                                                <h3 style={{ fontSize: '16px', marginBottom: '4px' }}>{job.title}</h3>
                                                <div style={{ fontSize: '13px', color: 'rgba(17,17,17,0.6)' }}>
                                                    {job.location} • {job.experience} Exp
                                                </div>
                                            </div>
                                            <div style={{ textAlign: 'right', display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' }}>
                                                <Badge variant={getScoreBadgeVariant(score)}>{score}% Match</Badge>
                                                <Button
                                                    variant="secondary"
                                                    style={{ fontSize: '11px', padding: '4px 10px', minHeight: 'auto' }}
                                                    onClick={() => window.open(job.applyUrl, '_blank')}
                                                >
                                                    Apply
                                                </Button>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>

                            <div style={{ padding: '24px', backgroundColor: 'rgba(17,17,17,0.02)', textAlign: 'center', fontSize: '12px', color: 'rgba(17,17,17,0.4)', borderTop: '1px solid var(--border-color)' }}>
                                This digest was generated based on your precision preferences.
                                <br />© 2026 KodNest Recruitment Platform.
                            </div>
                        </Card>
                    </div>
                )}
            </div>
        </div>
    );
};

export default DigestPage;
